name: Container Images

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'images/**'

  push:
    branches:
      - main
    paths:
      - 'images/**'
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * 0"
permissions:
  contents: write
  packages: write

env:
  PLATFORMS: linux/amd64

jobs:
  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    runs-on: ubuntu-latest
    outputs:
      custom-error-pages: ${{ steps.filter.outputs.custom-error-pages }}
      cfssl: ${{ steps.filter.outputs.cfssl }}
      fastcgi-helloserver: ${{ steps.filter.outputs.fastcgi-helloserver }}
      e2e-test-echo: ${{ steps.filter.outputs.e2e-test-echo }}
      go-grpc-greeter-server: ${{ steps.filter.outputs.go-grpc-greeter-server }}
      httpbun: ${{ steps.filter.outputs.httpbun }}
      kube-webhook-certgen: ${{ steps.filter.outputs.kube-webhook-certgen }}
      ext-auth-example-authsvc: ${{ steps.filter.outputs.ext-auth-example-authsvc }}
      nginx: ${{ steps.filter.outputs.nginx }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            custom-error-pages:
              - 'images/custom-error-pages/**'
            cfssl:
              - 'images/cfssl/**'
            fastcgi-helloserver:
              - 'images/fastcgi-helloserver/**'
            e2e-test-echo:
              - 'images/e2e-test-echo/**'
            go-grpc-greeter-server:
              - 'images/go-grpc-greeter-server/**'
            httpbun:
              - 'images/httpbun/**'
            kube-webhook-certgen:
              - 'images/kube-webhook-certgen/**'
            ext-auth-example-authsvc:
              - 'images/ext-auth-example-authsvc/**'
            nginx:
              - 'images/nginx/**'

  cfssl:
    permissions:
      contents: write
      packages: write
    needs: changes
    if: |
      (needs.changes.outputs.cfssl == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/zz-tmpl-images.yaml
    with:
      name: cfssl
    secrets: inherit

  custom-error-pages:
    permissions:
      contents: write
      packages: write
    needs: changes
    if: |
      (needs.changes.outputs.custom-error-pages == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/zz-tmpl-images.yaml
    with:
      name: custom-error-pages
    secrets: inherit

  e2e-test-echo:
    permissions:
      contents: write
      packages: write
    needs: changes
    if: |
      (needs.changes.outputs.e2e-test-echo == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/zz-tmpl-images.yaml
    with:
      name: e2e-test-echo
    secrets: inherit

  ext-auth-example-authsvc:
    permissions:
      contents: write
      packages: write
    needs: changes
    if: |
      (needs.changes.outputs.ext-auth-example-authsvc == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/zz-tmpl-images.yaml
    with:
      name: ext-auth-example-authsvc
    secrets: inherit

  fastcgi-helloserver:
    permissions:
      contents: write
      packages: write
    needs: changes
    if: |
      (needs.changes.outputs.fastcgi-helloserver == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/zz-tmpl-images.yaml
    with:
      name: fastcgi-helloserver
    secrets: inherit

  go-grpc-greeter-server:
    permissions:
      contents: write
      packages: write
    needs: changes
    if: |
      (needs.changes.outputs.go-grpc-greeter-server == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/zz-tmpl-images.yaml
    with:
      name: go-grpc-greeter-server
    secrets: inherit

  httpbun:
    permissions:
      contents: write
      packages: write
    needs: changes
    if: |
      (needs.changes.outputs.httpbun == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/zz-tmpl-images.yaml
    with:
      name: httpbun
    secrets: inherit

  kube-webhook-certgen-push:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (needs.changes.outputs.kube-webhook-certgen == 'true')
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Get go version
      run: echo "GOLANG_VERSION=$(cat GOLANG_VERSION)" >> $GITHUB_ENV

    - name: Set up Go
      id: go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ env.GOLANG_VERSION }}
        check-latest: true
    - name: Login to GitHub Container Registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: image build
      run: |
        cd images/ && make REGISTRY=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/ingress-nginx NAME=kube-webhook-certgen push


  kube-webhook-certgen:
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (needs.changes.outputs.kube-webhook-certgen == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    strategy:
      fail-fast: false
      matrix:
        k8s: [v1.31.14, v1.32.11, v1.33.7, v1.34.3, v1.35.1]
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Get go version
      run: echo "GOLANG_VERSION=$(cat GOLANG_VERSION)" >> $GITHUB_ENV

    - name: Set up Go
      id: go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ env.GOLANG_VERSION }}
        check-latest: true
    - name: image build
      run: |
        cd images/ && make NAME=kube-webhook-certgen build
    - name: Create Kubernetes cluster
      id: kind
      run: |
        kind create cluster --image=kindest/node:${{ matrix.k8s }}
    - name: image test
      run: |
        cd images/ && make NAME=kube-webhook-certgen test test-e2e

  nginx:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.nginx == 'true') || (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    env:
      PLATFORMS: linux/amd64,linux/arm,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          version: latest
          platforms: ${{ env.PLATFORMS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set push flag
        run: |
          if [[ '${{ github.event_name }}' == 'push' && '${{ github.ref }}' == 'refs/heads/main' && '${{ needs.changes.outputs.nginx }}' == 'true' ]]; then
            echo "PUSH_FLAG='--push'"
            echo "PUSH_FLAG='--push'" >> $GITHUB_ENV
          else
            echo "PUSH_FLAG="
          fi
      - name: build-rootfs-image
        run: |
          export TAG=$(cat images/nginx/TAG)
          export IMG_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/ingress-nginx/nginx
          cd images/nginx/rootfs && docker buildx build --platform=${{ env.PLATFORMS }} $PUSH_FLAG -t ${IMG_NAME}:${TAG} .
